Architecture: "channel-u-net"

Seed: 42

Setting: "en21-std"

Logger:
    save_dir: "experiments/"

Checkpointer:
    save_top_k: 1
    save_last: True
    period: 1

Trainer:
    gpus: 6
    accelerator: 'ddp'
    #deterministic: True
    log_every_n_steps: 32
    #profiler: 'advanced'
    #fast_dev_run: True
    #log_gpu_memory: 'all'
    #weights_summary: 'full'
    max_epochs: 20
    #limit_train_batches: 128
    #limit_val_batches: 64
  
Data:
    base_dir: /tmp/data/  #"/scratch/EarthNet2021/" #"/workspace/EarthNet2021/earthnet-model-intercomparison-suite/data/datasets/release/" #"/tmp/data/release/" #"/workspace/EarthNet2021/earthnet-model-intercomparison-suite/data/datasets/release/"
    #landcover_folder: /tmp/data/landcover/ # "/BGI/scratch/EarthNet2021/data/datasets/release/landcover/" #"/tmp/data/release/landcover/"
    test_track: "iid"
    noisy_masked_pixels: False
    use_meso_static_as_dynamic: True
    val_pct: 0.01
    train_batch_size: 96
    val_batch_size: 16
    test_batch_size: 96
    num_workers: 2

Task:
    loss:
        name: "masked"
        args: {
            distance_type: "L1"
        }
        dist_scale: 1
        state_shedule: {
            initial_weight: 0,
            increase_from_step: 1500,
            weight_step: 0.00001,
            max_weight: 1
        }
        inference_shedule: {
            initial_weight: 0,
            increase_from_step: 3000,
            weight_step: 0.0000000001,
            max_weight: 1
        }
        residuals_shedule: {
            initial_weight: 0,
            increase_from_step: 1500,
            weight_step: 0.00001,
            max_weight: 1
        }
        ndvi: False
    context_length: 10
    target_length: 20
    n_stochastic_preds: 1
    optimization:
        optimizer:
            - 
                name: 'Adam'
                args: 
                    betas: [0.9, 0.999]
                lr_per_sample: 0.0002
        lr_shedule:
            -
                name: 'MultiStepLR'
                args:
                    milestones: [40,70,90] #[2, 20, 50, 90]
                    gamma: 0.1
    n_log_batches: 2
    compute_metric_on_test: True

Model:
    name: "Unet"
    args: 
        encoder_name: "densenet161"
        encoder_weights: "imagenet"
        in_channels: 191
        classes: 80
        activation: "sigmoid"
    noisy_pixel_mask: True
    predictors: True
    hr_head: False
